=== VijayEluri/jaguar/src/jaguar/dtd/turing.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT sym (#PCDATA)>

<!ELEMENT alph (sym)*>

<!ELEMENT str (sym)+>

<!ELEMENT epsilon EMPTY>

<!ELEMENT state (#PCDATA)>

<!ATTLIST state xpos CDATA #IMPLIED
                ypos CDATA #IMPLIED>

<!ELEMENT stateSet (state)*>

<!ELEMENT description (#PCDATA)>

<!-- Aquí comienza, propiamente la definición de un DFA --> 

<!ELEMENT left EMPTY>

<!ELEMENT right EMPTY>

<!ELEMENT QxGammaxDirection (state, sym, (left|right))>

<!ELEMENT trans (state, sym, QxGammaxDirection)>

<!ELEMENT delta (trans)*>

<!ELEMENT turing (stateSet, alph, alph, delta, state, sym, stateSet)>

=== VijayEluri/jaguar/test/machine/tm/tm-0-2-radical-n.xml
<?xml version='1.0' encoding="iso-8859-1" ?>
<!DOCTYPE turing SYSTEM "turing.dtd">

<turing>

<description>Acepta el lenguaje L = { 0^{2^{n}} | n >= 0}</description>

<stateSet>
  <state>q1</state>
  <state>q2</state>
  <state>q3</state>
  <state>q4</state>
  <state>q5</state>
  <state>qaccept</state>
  <state>qreject</state>
</stateSet>

<alph>
  <sym>0</sym>
</alph>

<alph>
  <sym>x</sym> <sym>_</sym>
</alph>

<delta>

  <trans> <state>q1</state> <sym>0</sym>
    <QxGammaxDirection> <state>q2</state> <sym>_</sym> <right/> </QxGammaxDirection>
  </trans>

  <trans> <state>q1</state> <sym>_</sym>
      <QxGammaxDirection>
      <state>qreject</state>
      <sym>_</sym><right/></QxGammaxDirection>
  </trans>

  <trans> <state>q1</state> <sym>x</sym><QxGammaxDirection> <state>qreject</state> <sym>x</sym> <right/> </QxGammaxDirection>
  </trans>

  <trans> <state>q2</state> <sym>x</sym><QxGammaxDirection> <state>q2</state> <sym>x</sym> <right/></QxGammaxDirection>
  </trans>

  <trans> <state>q2</state>
  <sym>_</sym><QxGammaxDirection>
      <state>qaccept</state>
      <sym>_</sym><right/></QxGammaxDirection>
  </trans>

  <trans> <state>q2</state>
  <sym>0</sym><QxGammaxDirection>
      <state>q3</state>
      <sym>x</sym><right/></QxGammaxDirection>
  </trans>

  <trans> <state>q3</state>
  <sym>x</sym><QxGammaxDirection>
      <state>q3</state>
      <sym>x</sym><right/></QxGammaxDirection>
  </trans>
  <trans> <state>q3</state>
  <sym>_</sym><QxGammaxDirection>
      <state>q5</state>
      <sym>_</sym><left/></QxGammaxDirection>
  </trans>

  <trans> <state>q3</state>
  <sym>0</sym><QxGammaxDirection>
      <state>q4</state>
      <sym>0</sym><right/></QxGammaxDirection>
  </trans>

  <trans> <state>q4</state>
  <sym>x</sym><QxGammaxDirection>
      <state>q4</state>
      <sym>x</sym><right/></QxGammaxDirection>
  </trans>

  <trans> <state>q4</state>
  <sym>0</sym><QxGammaxDirection>
      <state>q3</state>
      <sym>x</sym><right/></QxGammaxDirection>
  </trans>

  <trans> <state>q5</state>
  <sym>0</sym><QxGammaxDirection>
      <state>q5</state>
      <sym>0</sym><left/></QxGammaxDirection>
  </trans>

  <trans> <state>q5</state>
  <sym>x</sym><QxGammaxDirection>
      <state>q5</state>
      <sym>x</sym><left/></QxGammaxDirection>
  </trans>

  <trans> <state>q5</state>
  <sym>_</sym><QxGammaxDirection>
      <state>q2</state>
      <sym>_</sym><right/></QxGammaxDirection>
  </trans>
</delta>

<state>q1</state>

<sym>_</sym>

<stateSet> <state>qaccept</state>  </stateSet>


</turing>

=== VijayEluri/jaguar/test/machine/tm/tm-an-bn.xml
<?xml version='1.0' encoding="iso-8859-1" ?>
<!DOCTYPE turing SYSTEM "turing.dtd">

<turing>

<description>Reconoce el lenguaje {0^n1^n | n > 0}</description>

<!--   El conjunto de estados  Q -->

	<stateSet> 
		<state>q0</state>
		<state>q1</state>
		<state>q2</state>
		<state>q3</state>
		<state>q4</state>
		<state>q5</state>
	</stateSet>

<!--   El alphabeto Sigma -->

	<alph>
		<sym>0</sym> <sym>1</sym>
	</alph>

<!--   El alphabeto Gamma -->

	<alph>
		<sym>0</sym> <sym>1</sym> <sym>_</sym> <sym>X</sym> <sym>Y</sym>
	</alph>

<!--   La función de transición Delta -->

	<delta>
		<trans> <state>q0</state> <sym>0</sym>
			<QxGammaxDirection> <state>q1</state> <sym>X</sym> <right/> </QxGammaxDirection>
		</trans>

		<trans> <state>q1</state> <sym>0</sym>
			<QxGammaxDirection> <state>q1</state> <sym>0</sym> <right/> </QxGammaxDirection>
		</trans>
		<trans> <state>q1</state> <sym>1</sym>
			<QxGammaxDirection> <state>q2</state> <sym>Y</sym> <left/> </QxGammaxDirection>
		</trans>
		<trans> <state>q1</state> <sym>Y</sym>
			<QxGammaxDirection> <state>q1</state> <sym>Y</sym> <right/> </QxGammaxDirection>
		</trans>

		<trans> <state>q2</state> <sym>0</sym>
			<QxGammaxDirection> <state>q4</state> <sym>0</sym> <left/> </QxGammaxDirection>
		</trans>

		<trans> <state>q2</state> <sym>X</sym>
			<QxGammaxDirection> <state>q3</state> <sym>X</sym> <right/> </QxGammaxDirection>
		</trans>

		<trans> <state>q2</state> <sym>Y</sym>
			<QxGammaxDirection> <state>q2</state> <sym>Y</sym> <left/> </QxGammaxDirection>
		</trans>

		<trans> <state>q3</state> <sym>Y</sym>
			<QxGammaxDirection> <state>q3</state> <sym>Y</sym> <right/> </QxGammaxDirection>
		</trans>

		<trans> <state>q3</state> <sym>_</sym>
			<QxGammaxDirection> <state>q5</state> <sym>Y</sym> <right/> </QxGammaxDirection>
		</trans>

		<trans> <state>q4</state> <sym>0</sym>
			<QxGammaxDirection> <state>q4</state> <sym>0</sym> <left/> </QxGammaxDirection>
		</trans>

		<trans> <state>q4</state> <sym>X</sym>
			<QxGammaxDirection> <state>q0</state> <sym>X</sym> <right/> </QxGammaxDirection>
		</trans>
	</delta>



<!--   El estado  -->

	<state>q0</state>

<!--   El blanco  -->

	<sym>_</sym>

<!--   El conjunto de estados finales -->

	<stateSet>
		<state>q5</state>
	</stateSet>

</turing>
